
[build]
  base = "botica-frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://tu-backend-railway.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
